### ISSUE TITLE
HTTP Error when predicting from a time series model

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_python_sdk#31]
* Python version: 3.8.5
* Operating system: Ubuntu 20
* Mindsdb Python SDK version: latest stable, 0.14

Running the following code snippet works for a "normal" predictor trained on Boston Housing dataset:

```python
from mindsdb_sdk import SDK

sdk = SDK('http://localhost:47334')
pred_name = 'bh'
predictor = sdk.predictors[pred_name]
ps = predictor.predict(when_data={'AGE': 2})
```

However, doing the same for a time series predictor yields the following error:

```
HTTPError                                 Traceback (most recent call last)
/MindsDB/mindsdb_python_sdk/mindsdb_sdk/classes/proxy.py in wrapper(*args, **kwargs)
     12         try:
---> 13             r.raise_for_status()
     14         except Exception as e:

/MindsDB/nenv/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 

HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:47334/api/predictors/COVID_SINGLE/predict_datasource

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-14-add5a55f3985> in <module>
      3     ps = predictor.predict(when_data={'AGE': 2})
      4 elif 'COVID' in pred_name:
----> 5     ps = predictor.predict(when_data=df)

/MindsDB/mindsdb_python_sdk/mindsdb_sdk/classes/predictors.py in predict(self, when_data, args)
     43 
     44         self.wait_readiness()
---> 45         return self._proxy.post(url, json=json)
     46 
     47     def _check_datasource(self, df):

/MindsDB/mindsdb_python_sdk/mindsdb_sdk/classes/proxy.py in wrapper(*args, **kwargs)
     13             r.raise_for_status()
     14         except Exception as e:
---> 15             raise Exception(f"Error with message: {r.text}") from e
     16         return r.json()
     17     return wrapper

Exception: Error with message: {"message": "Fault: <Fault 1: \"<class 'ValueError'>:No objects to concatenate\">"}

```

EDIT: here is the respective MindsDB log:

```
INFO:mindsdb-logger-core-logger---:/MindsDB/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

ERROR:mindsdb-logger-core-logger---:/MindsDB/mindsdb_native/mindsdb_native/libs/controllers/transaction.py:173 - Could not load module ModelInterface

127.0.0.1 - - [06/Apr/2021 11:14:38] "POST / HTTP/1.1" 200 -
http exception: <Fault 1: "<class 'ValueError'>:No objects to concatenate">
[2021-04-06 11:14:38,574] ERROR in app: Exception on /api/predictors/COVID_SINGLE/predict_datasource [POST]
Traceback (most recent call last):
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/MindsDB/mindsdb/mindsdb/api/http/namespaces/predictor.py", line 219, in post
    results = ca.naitve_interface.predict(name, format_flag, when_data=from_data, **kwargs)
  File "/MindsDB/mindsdb/mindsdb/interfaces/model/model_interface.py", line 29, in predict
    bin = self.proxy.predict(name, pred_format, when_data, kwargs)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'ValueError'>:No objects to concatenate">

ERROR:mindsdb.api.http.initialize:Exception on /api/predictors/COVID_SINGLE/predict_datasource [POST]
Traceback (most recent call last):
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/MindsDB/nenv/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/MindsDB/mindsdb/mindsdb/api/http/namespaces/predictor.py", line 219, in post
    results = ca.naitve_interface.predict(name, format_flag, when_data=from_data, **kwargs)
  File "/MindsDB/mindsdb/mindsdb/interfaces/model/model_interface.py", line 29, in predict
    bin = self.proxy.predict(name, pred_format, when_data, kwargs)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'ValueError'>:No objects to concatenate">
```

**Comment by paxcema** [comment]
Issue does not trigger for a predictor trained with the same dataset and configuration, except for unmarking the group-by column :thinking:

**Comment by George3d6** [comment]
New release solves this, apparently calling `.predict` with dictionary for `when` was always broken but it was only detected in this instance.
