### ISSUE TITLE
Calling project.list_models() with no models results in Exception

### ISSUE THREAD

**Issue by radiantone** [mindsdb/mindsdb_python_sdk#72]
**Your Environment**

* Python version: 3.10
* Operating system: Pop!_OS 22.04
* Mindsdb Python SDK version: mindsdb-sdk==1.0.4
mindsdb-sql==0.6.7

* Additional info if applicable:
project.list_models() should return [] if no models are present. The "models" table should be created by default if it is missing.

INFO:werkzeug:127.0.0.1 - - [18/Sep/2023 04:20:21] "GET /minds/project/Inference/models HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask_restx/api.py", line 675, in error_router
    return original_handler(e)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask_restx/api.py", line 675, in error_router
    return original_handler(e)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/darren/PycharmProjects/pyfi/pyfi/server/api.py", line 229, in decorated
    return f(*args, **kwargs)
  File "/home/darren/PycharmProjects/pyfi/pyfi/server/api.py", line 1439, in list_models
    models = project.list_models()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/project.py", line 345, in list_models
    df = self.query(ast_query.to_string()).fetch()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/query.py", line 29, in fetch
    return self.api.sql_query(self.sql, self.database)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/connectors/rest_api.py", line 11, in wrapper
    return fnc(self, *args, **kwargs)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/connectors/rest_api.py", line 82, in sql_query
    raise RuntimeError(data['error_message'])
RuntimeError: Error in Inference: no such table: models

**Comment by ea-rus** [comment]
Can't replicate this error
What version of mindsdb are you using: cloud or local or managed instance?

If you go to mindsdb web interface and execute these command will you see any error?

```sql
-- switch current project
use <project name here>;

-- list of models
select * from models

```

**Comment by radiantone** [comment]
I'm using the docker image: mindsdb/mindsdb, what port is the UI, I am only using the python sdk

**Comment by radiantone** [comment]
This only seems to happen for one of my projects. I create them through the python sdk. Let me delete it and see if I can isolate why that project object is messed up. It gives errors in the UI trying to browse it as well.

**Comment by radiantone** [comment]
> Can't replicate this error What version of mindsdb are you using: cloud or local or managed instance?
> 
> If you go to mindsdb web interface and execute these command will you see any error?
> 
> ```sql
> -- switch current project
> use <project name here>;
> 
> -- list of models
> select * from models
> ```

This worked in the UI without any error. Even on my project that is messed up.

**Comment by ea-rus** [comment]
What is the broken project name, does it content no [A-z0-9] symbols?

**Comment by radiantone** [comment]
It's called 'Inference' with capital I
![image](https://github.com/mindsdb/mindsdb_python_sdk/assets/25509097/883a4a63-a87f-4501-8c0d-756ae090efca)

**Comment by ea-rus** [comment]
What text of error message gui shows? 
If you can open network tab (in dev tools) and copy any addition info in response of error (traceback for example) it would be great

**Comment by radiantone** [comment]
![image](https://github.com/mindsdb/mindsdb_python_sdk/assets/25509097/e772358a-5c18-4d4e-8ce4-e3577a980b02)

{"message": "AttributeError: 'NoneType' object has no attribute 'rename'"}

**Comment by ea-rus** [comment]
I noticed that you have database with the same name 'Inference'. I think it is the cause of the problem. Mindsdb server can use mess database and project to execute queries.
We need to check name of the project. I will create issue in mindsdb repo

**Comment by radiantone** [comment]
Yeah, looks like there is a name collision happening. mindsdb should properly namespace or separate database names that are used in different engine types e.g. "sqllite.Inference" "mindsdb.Inference" or prevent the second Inference name.

**Comment by ea-rus** [comment]
The project/database name must be unique because they are root objects. This check will be implemented in https://github.com/mindsdb/mindsdb/issues/7365
